spring:
  datasource:
    url: jdbc:mysql://122.152.217.99:3306/normal_resource?useUnicode=true&characterEncoding=utf-8
    username: admin
    password: coomhefei123$%^
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-test-query: select 1
      max-lifetime: 20000
mybatis:
  mapper-locations: classpath*:/mapper/*.xml

