spring:
  datasource:
    url: jdbc:mysql://122.152.217.99:3306/normal_resource?useUnicode=true&characterEncoding=utf-8
    username: admin
    password: coomhefei123$%^
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      idle-timeout: 60000
      connection-test-query: select 1

mybatis:
  mapper-locations: classpath*:/mapper/*.xml
  configuration:
    call-setters-on-nulls: true

# open api config
openapi:
  taobao:
    adzoneid: 110670800125
    appkey: 30963536
    appsecret: 8da2478ae2d25c96ebde05cf3f522e7f
    serverurl: http://gw.api.taobao.com/router/rest
    userid: 1309050177
    materialids: 13369,31362,31371,4094,3756,3786,13366
    images:
      path: E:/pics/tmp/
  pdd:
    pid: 11136444_175955262
    appkey: 66acc0f56ee545c48ff7748c10d4f871
    appsecret: 68cd9546b762345ad9dd5725a5f00edcf9912076



