spring:
  datasource:
    url: jdbc:mysql://122.152.217.99:3306/normal_resource?useUnicode=true&characterEncoding=utf-8
    username: admin
    password: coomhefei123$%^
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      idle-timeout: 180000
      connection-test-query: select 1

mybatis:
  mapper-locations: classpath*:/mapper/*.xml

# auto send
autosend:
  groups: 文件传输助手
  sendinterval:
    seconds: 5
  images:
    path: E:/pics/tmp/
  strategy: boundMaterialVote

  taobao:
    adzoneid: 110670800125
    appkey: 30963536
    appsecret: 8da2478ae2d25c96ebde05cf3f522e7f
    serverurl: http://gw.api.taobao.com/router/rest
    userid: 1309050177
    materialids: 13369,31362,31371,4094,3756,3786,13366
  webchat:
    location: E:/soft-install-here/WeChat/WeChat.exe
#order pay
biz:
  client:
    alipay:
      order:
        query:
          url: ''
    connect:
      ip: 127.0.0.1
      port: 7001
      timeout:
        millis: 5000
    query:
      interval: 5000
    wb:
      connect:
        uri: ws://127.0.0.1:7001/websocket
    write:
      timeout:
        seconds: 60
